server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eduinsuncheon?serverTimezone=Asia/Seoul
    username: root
    password: 820318

  security:
    user:
      name: root
      password: root
      roles: ADMIN

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      # 나중엔 update로 변경해야함.
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false
  groovy:
    template:
      allow-request-override:


logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

root.key: e0860e978d4368033b5c758cfd4b537e